### ISSUE TITLE
Uncaught TypeError: this.element.querySelector is not a function

### ISSUE THREAD

**Issue by shankuo** [coronalabs/CoronaSDK-AtomPlugin#3] opened 2017-05-30 01:37 UTC
[Enter steps to reproduce:]

In the search box, type corona and hit enter. The autocomplete-corona package should show as the first option. Click on the Install button. This will install the package and you can start using it immediately.

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [autocomplete-corona](https://github.com/coronalabs/CoronaSDK-AtomPlugin) package 1.0.7

### Stack Trace

Uncaught TypeError: this.element.querySelector is not a function

```
At C:\Users\Unity\.atom\packages\autocomplete-corona\node_modules\atom-package-deps\lib\view.js:41

TypeError: this.element.querySelector is not a function
    at View.advance (/packages/autocomplete-corona/node_modules/atom-package-deps/lib/view.js:41:36)
    at /packages/autocomplete-corona/node_modules/atom-package-deps/lib/main.js:53:16
    at stdout (/packages/autocomplete-corona/node_modules/atom-package-deps/lib/helpers.js:24:11)
    at Socket.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/buffered-process.js:212:1)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

### Commands

```
     -1:05.1.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-corona 1.0.7 
language-lua 0.9.11 
```

**Comment by vavilin** [comment] 2017-06-23 08:02
+1 I got the same error, no one solutions how to resolve it?

**Comment by TailyFair** [comment] 2017-08-01 14:33
Having same issue.

**Comment by Shchvova** [comment] 2017-08-24 16:20
Duplicate of #4

**Closed as completed by Shchvova** 2017-08-24 16:20 UTC
